name: Time Stamp
on: push
jobs:
 getTimeStamp:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: get_current_date
        run: |
         echo "currentdate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
         echo "${{ steps.get_current_date.outputs.currentdate }}"
